#!/usr/bin/perl
# POD {{{
=head1 NAME

tb - Manage projects by throwing them into and out of Tarballs

=head1 SYNOPSIS

	tb [options] <projects> 

=head1 OPTIONS

=over 8

=item B<--dryrun>

=item B<-n>

Do not actually run any system commands. Just output what WOULD run.

=item B<--delete>

=item B<-d>

Delete a project from the active folder after tarballing.

=item B<--info>

=item B<-i>

Show information about projects.

=item B<--list>

=item B<-l>

List all known active projects and tarballs.

=item B<--force>

=item B<-f>

If specified during normal operation this option forces a tarball to be created even if the tarball is the same age as the most recent file.
If specified during a recovery action, any existing files are overritten during the recovery.

=item B<--meld>

=item B<--merge>

=item B<-m>

Extract the tarball a temporary directory (see --path-temp) then run 'meld' over the temporary and active project directories to highlight the differences.

=item B<--path-projects>

Set the root directory of extractd projects. The environment variable TBPROJECTS can also be set to automatically specify this item.

=item B<--path-tarballs>

Set the root directory of tarballs. The environment variable TBTARBALLS can also be set to automatically specify this item.

=item B<--path-temp>

Set the root directory for temporary files using when melding (see --meld). The environment variable TBTEMP can also be set to automatically specify this item.

=item B<--recover>

=item B<--reverse>

=item B<-r>

Reverse the backup process so the backup is restored over the active version.
If an active version of a project already exists this function will not continue unless force (-f) is specified.

=item B<-v>

=item B<--verbose>

Be more verbose when outputting information to STDERR.
Specify multiple times to increase verbosity.

=back

=head1 DESCRIPTION

A command line tool for the manipulation of projects.

=head1 EXAMPLES

=over

=item B<tb foo>

Tarball the project 'foo' to backup.
If the tarball already exists and is up to date the project will be skipped (to override this behaviour use '-f').

=item B<tb -d foo>

Tarball the project 'foo' to backup and delete the original active folder afterwards.

=item B<tb -r foo>

Recover the tarballed project 'foo' from backup into an active project folder.
If 'foo' already exists it will NOT be overwritten.

=item B<tb -rf foo>

Same as above but this time if 'foo' does exist it will be removed before the restore takes place.

=item B<tb -l>

List all known projects (both tarballs and active)

=back

=head1 BUGS

Quite probably.

Please report to the author when found.

=head1 AUTHOR

Matt Carter <m@ttcarter.com>

=cut
# }}} POD

package tb;
our $VERSION = '0.1.0';

# Header {{{
use IO::Handle;
use Getopt::Long;
use POSIX qw/strftime/;
Getopt::Long::Configure('bundling', 'ignorecase_always', 'pass_through');
STDERR->autoflush(1); # } Flush the output DIRECTLY to the output buffer without caching
STDOUT->autoflush(1); # }

use Data::Dump; # FIXME: Debugging modules
# }}} Header

# Functions {{{
# Flow control {{{
sub fatal {
	# Print an error message and fatally die
	print STDERR @_, "\n";
	exit 1;
}

sub say {
	# Print a message to STDERR based on the verbosity level
	our $verbose;
	my $verbosity = shift;
	print STDERR @_, "\n" if ($verbose >= $verbosity);
}

sub pause {
	# Wait a number of seconds (specified by the -w [seconds]) between VM operations
	# This function purposely ignores the first vm (thus not bothering to wait for the last vm to finish)
	our $wait;
	if ($wait > 0) {
		say(0, "Waiting $wait seconds...");
		sleep($wait);
	}
}

sub error {
	my $action = shift;
	my $subject = shift;
	if (ref($@) eq 'SoapFault') {
		say(0, "ERROR: " . $@->detail);
	} else {
		say(0, "ERROR: General fault!");
	}
	fatal("Stopping execution. Use -f to force continue.") unless $force;
}
# }}} Flow control

sub run {
	our $dryrun;
	my $cmd = shift;
	if ($dryrun) {
		say 0, "Would run command: [$cmd]";
		return 1;
	} else {
		$return = system $cmd;
		return $return == 0 ? true : false;
	}
}

sub getrecent {
	my $dir = shift;
	my $recent = undef;
	say 2, "Scan dir '$_'";
	for (glob("$dir/*")) {
		my $mtime;
		if (-d) {
			$mtime = getrecent($_);
		} elsif (-f) {
			my @stat = stat($_);
			$mtime = $stat[9];
		}
		$recent = $mtime if $mtime && ($mtime > $recent || !$recent);
		say 2, "Examine file '$_' Age = $mtime";
	}
	$recent;
}

sub gettbage {
	my $tarball = shift;
	if (-f $tarball) {
		my @stat = stat($tarball);
		$stat[9];
	}
}

# }}} Functions

# Command line options loading {{{
my $delete, $recover, $list, $info, $meld;
my $path_projects, $path_tarballs, $path_temp;
our $dryrun;
our $verbose = 0;
GetOptions(
	'list|l' => \$list,
	'meld|merge|m' => \$meld,
	'info|i' => \$info,
	'dryrun|n' => \$dryrun,
	'verbose|v+' => \$verbose,
	'delete|d' => \$delete,
	'recover|reverse|r' => \$recover,
	'force|f' => \$force,
	'path-projects=s' => \$path_projects,
	'path-tarballs=s' => \$path_tarballs,
	'path-temp=s' => \$path_temp,
);

my $projects, $tarballs, $temp;
if ($path_projects) {
	$projects = $path_projects;
} elsif ($ENV{TBPROJECTS}) {
	$projects = $ENV{TBPROJECTS};
} else {
	fatal "No project path specified. Use either --path-projects or set the environment variable TBPROJECTS";
}

if ($path_tarballs) {
	$tarballs = $path_tarballs;
} elsif ($ENV{TBTARBALLS}) {
	$tarballs = $ENV{TBTARBALLS};
} else {
	fatal "No tarball path specified. Use either --path-tarballs or set the environment variable TBTARBALLS";
}

if ($meld and $path_temp) {
	$temp = $path_temp;
} elsif ($ENV{TBTEMP}) {
	$temp = $ENV{TBTEMP};
} else {
	fatal "Cannot use --meld without also specifying a temporary directory. Use either --path-temp or set the environment variable TBTEMP with a temporary root directory";
}

say 2, "Using Projects path [$projects]";
say 2, "Using Tarball path [$tarballs]";
# }}} Command line options loading

chdir($projects) or fatal "Cannot change to projects root directory '$projects'";
fatal "Cannot find tarball root directory '$tarballs'" unless -d $tarballs;

$list = 1 unless (@ARGV); # Default to list mode if nothing else is requested

# List functionality (--list | -l) {{{
if ($list) {
	my $count_active = 0;
	my $count_tarballs = 0;
	my $count_both = 0;
	my $last;
	for my $project (sort map { s!^(.*)/(.*?)(\.tar\.bz2)?$!\2!; $_ } (glob("$projects/*"), glob("$tarballs/*.bz2"))) { # Return all files in both folders, clip out the directory + suffix, sort
		next if $project eq $last;
		$last = $project;
		my $hasall = 0;
		$out = '';
		if (-d "$projects/$project") {
			$out .=  '[A]';
			$count_active++;
			$hasall = 1;
		} else {
			$out .= '   ';
		}
		$out .= ' ';
		if (-f "$tarballs/$project.tar.bz2") {
			$out .= '[T]';
			$count_tarballs++;
			$count_both++ if $hasall = 1;
		} else {
			$out .= '   ';
		}
		$out .= " $project";
		say 0, $out;
	}

	say;
	say 0, "[A]ctive = $count_active, [T]arballs = $count_tarballs, Both = $count_both";
	exit;
}
# }}}

for my $project (@ARGV) {
	$project =~ s/\/$//; # Chop off backslash if any
	my $tarball = "$tarballs/$project.tar.bz2";
	say 1, "Operating on project '$project'";

	if ($recover) {
		# Recover functionality (--recover | -r) {{{
		fatal "Tarball '$tarball' not found when trying to recover project '$project'. Aborting" unless (-f $tarball);
		if (-d $project) { # Project folder exists
			if ($force) { # Permission to nuke it?
				run "rm -rf '$project'" or fatal "Cannot remove existing project folder '$project' to restore Tarball";
			} else {
				fatal "Project '$project' already exists when recovering project from Tarball. Use '-f' to force deletion of existing project.";
			}
		}
		run "mkdir '$project'" or fatal "Failed to create directory when recovering project '$project'";
		run "tar xvfj $tarball" or fatal "Failed to extract from Tarball when recovering project '$project'";
		# }}}
	} elsif ($info) {
		# Display information on project {{{
		my $youngest = getrecent($project);
		my $tbage = gettbage("$tarballs/$project.tar.bz2");
		say 0, "Project: '$project'";
		say 0, "Most recent file: " . (-d $project ? "$youngest / " . strftime('%d-%m-%Y %H:%M:%S', localtime $youngest) : 'No active project');
		say 0, "Tarball age: " . (-f "$tarballs/$project.tar.bz2" ? "$tbage / " . strftime('%d-%m-%Y %H:%M:%S', localtime $tbage) : 'No tarball');
		say 0, "Would update: " . ($tbage < $youngest ? 'Yes' : 'No');
		say;
		# }}}
	} elsif ($meld) {
		say 0, "Melding '$project'...";
		# Meld the tarball and project {{{
		fatal "Tarball '$tarball' not found when trying to meld project '$project'. Aborting" unless (-f $tarball);
		chdir($temp);
		run "tar xvfj $tarball" or fatal "Failed to extract from Tarball when melding project '$project'";
		run "mv '$project' 'TEMP-$project'" or fatal "Failed moving temporary directory when melding project '$project'";
		chdir($projects);
		run "meld '$project' '$temp/TEMP-$project'" or fatal "Failed running meld on project '$project'";
		run "rm -rf '$temp/TEMP-$project'" or fatal "Failed erasing temporary files during meld on project '$project'";
		# }}}
	} else {
		# Normal Tarball backup functionality {{{
		unless ($force) { # If forced just nuke the archive and re-created - if not try to figure out the newest file
			my $youngest = getrecent($project);
			my $tbage = gettbage("$tarballs/$project.tar.bz2");
			if ($tbage >= $youngest) {
				say 0, "Skipped '$project'";
				next;
			}
		}

		fatal "Project '$project' not found. Aborting" unless (-d $project);
		run "rm '$tarball'" or fatal "Failed to remove existing tarball - '$tarball'" if (-f $tarball);
		run "tar cvfj $tarball $project" or fatal "Failed to tarball project '$project'";
		run "rm -rf $project" or fatal "Failed to erased project tree for project '$project'" if $delete;
		# }}}
	}
}
